import { Demo } from "@/types/demo";

export const localDemos: Demo[] = [
  {
    id: "local-1",
    title: "Avukatlik Kurumsal V1",
    category: "avukat",
    slug: "avukatlik-kurumsal-v1",
    demo_url: "https://example.com/demo-law-1",
    preview_image:
      "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=1400&q=80",
    base_price: 12000,
    short_description: "Hukuk ofisleri icin guven odakli sade tasarim.",
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "local-2",
    title: "Emlak Portfoy Pro V1",
    category: "emlak",
    slug: "emlak-portfoy-pro-v1",
    demo_url: "https://example.com/demo-realty-1",
    preview_image:
      "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1400&q=80",
    base_price: 15000,
    short_description: "Portfoy odakli emlak satis sayfasi.",
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "local-3",
    title: "Fotografci Storyline V1",
    category: "fotografci",
    slug: "fotografci-storyline-v1",
    demo_url: "https://example.com/demo-photo-1",
    preview_image:
      "https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=1400&q=80",
    base_price: 10000,
    short_description: "Portfolyo vitrinini one cikaran modern yapi.",
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "local-4",
    title: "Emlak Villa Showcase V2",
    category: "emlak",
    slug: "emlak-villa-showcase-v2",
    demo_url: "https://example.com/demo-realty-2",
    preview_image:
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1400&q=80",
    base_price: 16500,
    short_description: "Luks konut portfoyleri icin premium duzen.",
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "local-5",
    title: "Emlak Yatirim Landing V3",
    category: "emlak",
    slug: "emlak-yatirim-landing-v3",
    demo_url: "https://example.com/demo-realty-3",
    preview_image:
      "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=1400&q=80",
    base_price: 17250,
    short_description: "Yatirim odakli ilan ve geri donusum kurgusu.",
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "local-6",
    title: "Dis Klinigi Modern V1",
    category: "dis-klinigi",
    slug: "dis-klinigi-modern-v1",
    demo_url: "https://example.com/demo-dental-1",
    preview_image:
      "https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=1400&q=80",
    base_price: 14000,
    short_description: "Klinikler icin modern ve temiz sunum deneyimi.",
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "local-7",
    title: "Dis Klinigi Randevu V2",
    category: "dis-klinigi",
    slug: "dis-klinigi-randevu-v2",
    demo_url: "https://example.com/demo-dental-2",
    preview_image:
      "https://images.unsplash.com/photo-1606811841689-23dfddce3e95?w=1400&q=80",
    base_price: 15200,
    short_description: "Randevu odakli donusum tasarimi.",
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "local-8",
    title: "Guzellik Salonu Glow V1",
    category: "guzellik-salonu",
    slug: "guzellik-salonu-glow-v1",
    demo_url: "https://example.com/demo-beauty-1",
    preview_image:
      "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=1400&q=80",
    base_price: 11250,
    short_description: "Hizmet odakli salon tanitim sayfasi.",
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "local-9",
    title: "Guzellik Salonu Booking V2",
    category: "guzellik-salonu",
    slug: "guzellik-salonu-booking-v2",
    demo_url: "https://example.com/demo-beauty-2",
    preview_image:
      "https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=1400&q=80",
    base_price: 12500,
    short_description: "Online randevuya yonlendiren sade duzen.",
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "local-10",
    title: "Insaat Kurumsal V1",
    category: "insaat",
    slug: "insaat-kurumsal-v1",
    demo_url: "https://example.com/demo-construction-1",
    preview_image:
      "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1400&q=80",
    base_price: 18500,
    short_description: "Insaat firmalari icin guven veren kurumsal cizgi.",
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "local-11",
    title: "Insaat Proje Portfoy V2",
    category: "insaat",
    slug: "insaat-proje-portfoy-v2",
    demo_url: "https://example.com/demo-construction-2",
    preview_image:
      "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=1400&q=80",
    base_price: 19800,
    short_description: "Tamamlanan projeleri one cikaran vitrin.",
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "local-12",
    title: "Danismanlik Executive V1",
    category: "danismanlik",
    slug: "danismanlik-executive-v1",
    demo_url: "https://example.com/demo-consulting-1",
    preview_image:
      "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1400&q=80",
    base_price: 16000,
    short_description: "B2B hizmet satisi icin ikna odakli yapi.",
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "local-13",
    title: "Danismanlik Premium V2",
    category: "danismanlik",
    slug: "danismanlik-premium-v2",
    demo_url: "https://example.com/demo-consulting-2",
    preview_image:
      "https://images.unsplash.com/photo-1552664730-d307ca884978?w=1400&q=80",
    base_price: 17500,
    short_description: "Premium hizmet sunumu icin temiz tasarim.",
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "local-14",
    title: "Kafe Bistro Landing V1",
    category: "kafe",
    slug: "kafe-bistro-landing-v1",
    demo_url: "https://example.com/demo-cafe-1",
    preview_image:
      "https://images.unsplash.com/photo-1445116572660-236099ec97a0?w=1400&q=80",
    base_price: 9800,
    short_description: "Mekan atmosferini one cikaran restoran sayfasi.",
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "local-15",
    title: "Restoran Menu Pro V2",
    category: "restoran",
    slug: "restoran-menu-pro-v2",
    demo_url: "https://example.com/demo-restaurant-1",
    preview_image:
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1400&q=80",
    base_price: 11800,
    short_description: "Online menu ve rezervasyon odakli akis.",
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "local-16",
    title: "Oto Galeri Showroom V1",
    category: "oto-galeri",
    slug: "oto-galeri-showroom-v1",
    demo_url: "https://example.com/demo-auto-1",
    preview_image:
      "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=1400&q=80",
    base_price: 14300,
    short_description: "Arac listeleme odakli showroom tasarimi.",
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "local-17",
    title: "Spor Salonu Membership V1",
    category: "spor-salonu",
    slug: "spor-salonu-membership-v1",
    demo_url: "https://example.com/demo-gym-1",
    preview_image:
      "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1400&q=80",
    base_price: 10800,
    short_description: "Uyelik donusumunu artiran fitness sayfasi.",
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "local-18",
    title: "Klinik Psikoloji V1",
    category: "psikolog",
    slug: "klinik-psikoloji-v1",
    demo_url: "https://example.com/demo-psychology-1",
    preview_image:
      "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=1400&q=80",
    base_price: 13200,
    short_description: "Guven ve sakinlik hissi veren klinik yapi.",
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "local-19",
    title: "Egitim Kurs Merkezi V1",
    category: "egitim",
    slug: "egitim-kurs-merkezi-v1",
    demo_url: "https://example.com/demo-education-1",
    preview_image:
      "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=1400&q=80",
    base_price: 11900,
    short_description: "Kurs kaydina yonlendiren egitim sitesi.",
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "local-20",
    title: "Yazilim Ajansi SaaS V1",
    category: "yazilim-ajansi",
    slug: "yazilim-ajansi-saas-v1",
    demo_url: "https://example.com/demo-software-1",
    preview_image:
      "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=1400&q=80",
    base_price: 21000,
    short_description: "Ajanslar icin premium B2B teklif vitrini.",
    is_active: true,
    created_at: new Date().toISOString(),
  },
];

export function hasSupabaseEnv() {
  return Boolean(
    process.env.NEXT_PUBLIC_SUPABASE_URL &&
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
  );
}
